baseurl      = ""
title        = "0xKirito's Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[author]
  name = "0xKirito"

[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  enableThemeToggle = true

  # Subtitle for home
  homeSubtitle = "My Cyber Security Journey"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  [params.footer]
    trademark = true
    rss = true
    author = false
    copyright = false

    topText = []
    bottomText = ["Powered by <a href=\"http://gohugo.io\">Hugo</a>",
            "Theme by <a href=\"https://github.com/rhazdon\">rhazdon</a>"]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "0xKirito"
    subtitle = "Cyber Security"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "0xKirito"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"

  [[menu.main]]
    identifier = "about"
    name = "About"
    weight = 2
    url = "/about/"


  # Social links

  [[params.social]]
    name = "twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/0xKirito"

  [[params.social]]
    name = "github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/0xKirito"

